#!/bin/bash
#
# Copyright 2002-2011 Graham Forest <vitaminmoo@wza.us> All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without modification, are
# permitted provided that the following conditions are met:
# 
#    1. Redistributions of source code must retain the above copyright notice, this list of
#       conditions and the following disclaimer.
# 
#    2. Redistributions in binary form must reproduce the above copyright notice, this list
#       of conditions and the following disclaimer in the documentation and/or other materials
#       provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY <COPYRIGHT HOLDER> ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
# The views and conclusions contained in the software and documentation are those of the
# authors and should not be interpreted as representing official policies, either expressed
# or implied, of Graham Forest
 
# To get the newest version of this script, please
# visit http://obsoleet.org/code
#
#####################################################################

#
# Dependencies:
# tar, gzip, bzip2, unace, unrar, unzip, 7z, lzma
# but only if you use them
#
#####################################################################

#
# Bugs, TODO:
#
#  o Needs to pass options (like -v) to called programs
#
#  o Need to add a which statement with decompressor missing error
#
#####################################################################

check_success() # Could've written this by myself. Took it
                # from jsmaby's minimal system's initscript
                # instead. Thanks jsmaby. - Raphael
{
  if [ "$?" == "0" ]; then
    echo -e " done\007" # Makes a beep when successful. - Raphael
  else
    echo -e " failed"
  fi
}

IAM=`basename "$0"` # Our name

if [ ! "$1" ]; then # Seems we've got Altzheimer, hmm?
    echo "$IAM: You must specify at least one file"
    exit 1
fi

for i in "$@"; do

    ITIS=`basename "$i"` # Name of file (for output)

    case "$i" in # Evaluating the filetype...

        # No compression at all
        *.tar)
            echo -n "$IAM: Unpacking tarball $ITIS..."
            tar xf "$i"
            check_success
            ;;

        # tar'd and gzip'd or compress'd
        *.tar.gz|*.tgz|.tar.Z|.tar.z)
            echo -n "$IAM: Decompressing and unpacking gzip'd tarball $ITIS..."
            gzip -dc "$i" | tar xf -
            check_success
            ;;

        # tar'd and bzip2'd
        *.tar.bz2|*.tbz2|*.pkg)
            echo -n "$IAM: Decompressing and unpacking bzip'd tarball $ITIS..."
            bzip2 -dc "$i" | tar xf -
            check_success
            ;;

        # tar'd and lzma'd, thanks  Michel Lang
        *.tar.lzma|*.tlz)
            echo -n "$IAM: Decompressing and unpacking lzma'd tarball $ITIS..."
            lzma -dc "$i" | tar xf -
            check_success
            ;;

        # gzip'd or compress'd
        *.gz|*.Z|*.z)
            echo -n "$IAM: Decompressing gzip archive $ITIS..."
            gzip -dc "$i" > `basename "$i" .gz`
            check_success
            ;;

        # bzip2'd
        *.bz2)
            echo -n "Decompressing bzip2 archive $ITIS...";
            bzip2 -dc "$i" > `basename "$i" .bz2`
            check_success
            ;;

        # lzma'd, thanks Michel Lang
        *.lzma)
            echo -n "Decompressing lzma archive $ITIS...";
            lzma -dc "$i" > `basename "$i" .lzma`
            check_success
            ;;

        # Packed with (Win)ACE
        *.ace)
            echo -n "$IAM: Unpacking WinACE archive $ITIS..."
            unace x "$i"
            check_success
            ;;

        # Packed with (Win)RAR
        *.rar)
            echo -n "$IAM: Unpacking WinRAR archive $ITIS..."
            unrar x "$i"
            check_success
            ;;

        # Classically zipped
        *.zip)
            echo -n "$IAM: Unpacking pkzip archive $ITIS..."
            unzip "$i"
            check_success
            ;;
        # Packed with 7zip, thanks Komoto
        *.7z)
            echo -n"$IAM: Unpacking 7zip archive $ITIS..."
            7z x "$i"
            check_success
            ;;
        # Ooops... people have wierd things, eh?
        *)
            echo "$IAM: $ITIS - Filetype unknown"
            ;;

    esac
done
